export const FETCH_ACCESSES_REQUEST = 'FETCH_ACCESSES_REQUEST'
export const FETCH_ACCESSES_SUCCESS = 'FETCH_ACCESSES_SUCCESS'
export const FETCH_ACCESSES_FAILURE = 'FETCH_ACCESSES_FAILURE'

export const STORE_ACCESS_REQUEST = 'STORE_ACCESS_REQUEST'
export const STORE_ACCESS_SUCCESS = 'STORE_ACCESS_SUCCESS'
export const STORE_ACCESS_FAILURE = 'STORE_ACCESS_FAILURE'

export const UPDATE_ACCESS_REQUEST = 'UPDATE_ACCESS_REQUEST'
export const UPDATE_ACCESS_SUCCESS = 'UPDATE_ACCESS_SUCCESS'
export const UPDATE_ACCESS_FAILURE = 'UPDATE_ACCESS_FAILURE'

export const DESTROY_ACCESS_REQUEST = 'DESTROY_ACCESS_REQUEST'
export const DESTROY_ACCESS_SUCCESS = 'DESTROY_ACCESS_SUCCESS'
export const DESTROY_ACCESS_FAILURE = 'DESTROY_ACCESS_FAILURE'