export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const STORE_POST_REQUEST = 'STORE_POST_REQUEST'
export const STORE_POST_SUCCESS = 'STORE_POST_SUCCESS'
export const STORE_POST_FAILURE = 'STORE_POST_FAILURE'

export const STORE_POST_COMMENT_REQUEST = 'STORE_POST_COMMENT_REQUEST'
export const STORE_POST_COMMENT_SUCCESS = 'STORE_POST_COMMENT_SUCCESS'
export const STORE_POST_COMMENT_FAILURE = 'STORE_POST_COMMENT_FAILURE'

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE'

export const DESTROY_POST_REQUEST = 'DESTROY_POST_REQUEST'
export const DESTROY_POST_SUCCESS = 'DESTROY_POST_SUCCESS'
export const DESTROY_POST_FAILURE = 'DESTROY_POST_FAILURE'

