export const FETCH_ROLE_ACCESSES_REQUEST = 'FETCH_ROLE_ACCESSES_REQUEST'
export const FETCH_ROLE_ACCESSES_SUCCESS = 'FETCH_ROLE_ACCESSES_SUCCESS'
export const FETCH_ROLE_ACCESSES_FAILURE = 'FETCH_ROLE_ACCESSES_FAILURE'